#! /bin/sh
# prerm script for fizmo-glktermw

set -e

case "$1" in
    remove|upgrade|deconfigure)
        update-alternatives --remove zcode-interpreter /usr/games/fizmo-glktermw-launcher
        ;;
    failed-upgrade)
        update-alternatives --remove zcode-interpreter /usr/games/fizmo-glktermw-launcher
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#

exit 0
